### ISSUE TITLE
Guns shouldn't clip

### ISSUE THREAD

**Issue by fatjosephina** [mcdonaldduncan/Untitled#166]
![image](https://user-images.githubusercontent.com/55261891/217721580-e7d9e6a4-8b0e-4e61-9b19-05776d2e8517.png)
Change rendering layer of guns so that they render on top of everything.

**Comment by mcdonaldduncan** [comment]
This is not a bug, it would be a feature enhancement

**Comment by fatjosephina** [comment]
![image](https://user-images.githubusercontent.com/55261891/219033244-3590791e-b0e5-420f-b289-24aeba224f86.png)
