### ISSUE TITLE
Add health pickups

### ISSUE THREAD

**Issue by Sebp23** [mcdonaldduncan/Untitled#86]
Add pickup objects that restores player health

**Comment by mcdonaldduncan** [comment]
Hey, I thought we were not necessarily ruling out health pickups but that we were going to try health on kills first to see how that feels. Thoughts?

**Comment by Sebp23** [comment]
Oh yeah I had forgotten we spoke about that. I think that's a cool idea. Would it be all kills that restore health? Or would things like distance to enemy matter? Or should we add melee mechanics and have that be what restores health?

**Comment by mcdonaldduncan** [comment]
I think melee might be a challenge to get feeling good but I think we should do it at some point. We could, however, just add them on kills within a certain distance for now, that should be pretty easy to implement.

Regardless of the option we land on eventually, I think a flow of red particle effects from the enemy to the player on a health stealing kill would be essential for feedback.

**Comment by Sebp23** [comment]
Absolutely. For now, I'll implement a system where the player gets health restored when killing an enemy from a certain distance. Do you think the amount of health gained should be a flat amount or based on the damage of the kill shot?
